### ISSUE TITLE
"Error: could not create namespace api client: resource name may not be empty"

### ISSUE THREAD

**Issue by bbortt** [postfinance/kubectl-vault_sync#1]
Hi guys

I'm kind of stuck with the following error:
```bash
+ vault_sync
+ kubectl vault_sync --namespace=$K8S_NAMESPACE --wait
Error: could not create namespace api client: resource name may not be empty
```

I think this means you do not support `--namespace` yet, right? Sadly, my `$KUBECONFIG` is readonly (using GitHub Actions).
*Edit:* Or could it be something else? :/

**Comment by djboris9** [comment]
Implemented namespace overriding by cli args with https://github.com/postfinance/kubectl-vault_sync/commit/4ea2ed2f16a74b70827315a0a444e9bc463751ff, can you please try the version from master and give me feedback if it works for you

**Comment by bbortt** [comment]
Hi @djboris9

Exactly, I cannot set the active namespace via `kubectl`. 

Just wanted to suggest that I look at the implementation of `--wait` and see what I can do. But you were a lot faster :D

Thank you very much. I'll try it this evening.

**Comment by bbortt** [comment]
I'm sorry.. but how do I compile this on localhost? 
I'm not fluent in `go`.. tried to look at the Travis-CI build, no chance :D I just navigated into `pkg/plugin` and executed `go build`. That results in (when executing the plugin):
```bash
+ kubectl vault_sync --namespace=qdrakeboo-alpha --wait
exec format error
```

**Comment by djboris9** [comment]
Do it that way (with a recent Go version):
```bash
export GO111MODULE=on
go build -o kubectl-bbortt ./cmd/
export PATH="$(pwd):$PATH"
kubectl bbortt ... # the plugin is registered as bbortt
```

**Comment by bbortt** [comment]
awesome, works like a charm! thank you very much.
```bash
+ kubectl vault_sync --namespace=${K8S_NAMESPACE} --wait
creating sync batch job to synchronize 'secret/k8s/${K8S_NAMESPACE}/' vault key
```
btw. will you release the update? makes my dockerfile look much cleaner ;)

**Comment by djboris9** [comment]
Here you go https://github.com/postfinance/kubectl-vault_sync/releases/tag/v0.2.0
